$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
compute: azureml:feature-engineering-compute
experiment_name: DSAI3202-lab2

inputs:
  sampled_data:
    type: uri_folder
    path: azureml:amazon_electronics_features_v1_sampled:4  

jobs:
  split:
    type: command
    component: azureml:split_dataset@latest
    inputs:
      data: 
        path: ${{parent.inputs.sampled_data}}
        mode: download  

  normalize_train:
    type: command
    component: azureml:normalize_text@latest
    inputs:
      data: ${{parent.jobs.split.outputs.train}}

  normalize_val:
    type: command
    component: azureml:normalize_text@latest
    inputs:
      data: ${{parent.jobs.split.outputs.val}}

  normalize_test:
    type: command
    component: azureml:normalize_text@latest
    inputs:
      data: ${{parent.jobs.split.outputs.test}}

  length_train:
    type: command
    component: azureml:review_length@latest
    inputs:
      data: ${{parent.jobs.normalize_train.outputs.out}}

  sentiment_train:
    type: command
    component: azureml:sentiment_analysis:3
    inputs:
      data: ${{parent.jobs.normalize_train.outputs.out}}
  tfidf:
    type: command
    component: azureml:tfidf_features:3
    inputs:
      data: ${{parent.jobs.normalize_train.outputs.out}}

  sbert_train:
    type: command
    component: azureml:semantic_embedding_features:5
    inputs:
      input_data: ${{parent.jobs.normalize_train.outputs.out}}

  capital_letters_train:
    type: command
    component: azureml:capital_letters_feature@latest
    inputs:
      data: ${{parent.jobs.normalize_train.outputs.out}}
      text_column: "review_text"

  merge_all:
    type: command
    component: azureml:merge_features:9
    inputs:
      length: ${{parent.jobs.length_train.outputs.out}}
      sentiment: ${{parent.jobs.sentiment_train.outputs.out}}
      tfidf: ${{parent.jobs.tfidf.outputs.out}}
      sbert: ${{parent.jobs.sbert_train.outputs.output_data}}
      capital_letters: ${{parent.jobs.capital_letters_train.outputs.out}}
    outputs:
      out:
        type: uri_folder