$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command
code: ../src
command: >-
  python train.py 
  --train_data ${{inputs.train_data}} 
  --val_data ${{inputs.val_data}} 
  --test_data ${{inputs.test_data}}
  --output ./outputs
inputs:
  train_data:
    type: uri_folder
    path: azureml:amazon_review_merged_features_train:5
  val_data:
    type: uri_folder
    path: azureml:amazon_review_merged_features_val:5
  test_data:
    type: uri_folder
    path: azureml:amazon_review_merged_features_test:5
environment: azureml:amazon_review_training_env:1
compute: azureml:Amazon-Lab-compute
display_name: amazon-sentiment-training
experiment_name: assignment2-training